# Generated by Django 5.2.5 on 2025-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seating_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
