# Generated by Django 5.2.5 on 2025-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0006_product_discount_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
