# Generated by Django 5.2.5 on 2025-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0007_product_description_alter_product_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='product_price',
            new_name='product_offer',
        ),
    ]
