# Generated by Django 5.2.5 on 2025-08-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furnitureapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subsentence',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
