# Generated by Django 5.2.5 on 2025-08-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0011_alter_product_offer_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subsentence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
